include: https://gitlab/Sensirion/Python/ci-config-python/raw/master/gitlab-ci-template-v2.yml

check_rst_syntax:
  extends: .check_rst_syntax_v2

check_editorconfig:
  extends: .check_editorconfig_v2

py2p7_linux_build:
  extends: .py2p7_linux_build_v2
  variables:
    PYTEST_ADDOPTS: '-m "not needs_device"'

py3p5_linux_build:
  extends: .py3p5_linux_build_v2
  variables:
    PYTEST_ADDOPTS: '-m "not needs_device"'


py2p7_32bit_win_build:
  extends: .py2p7_32bit_win_docker_build_v2
  variables:
    PYTEST_ADDOPTS: '-m "not needs_device"'

py3p5_64bit_win_build:
  extends: .py3p5_64bit_win_docker_build_v2
  variables:
    PYTEST_ADDOPTS: '-m "not needs_device"'


build_docs:
  extends: .build_docs_v2
  script:
    - apt-get update && apt-get install -y graphviz
    - python setup.py install
    - pip install -r docs/requirements.txt
    - ./ci/set_git_config.sh
    - sphinx-versioning build -r "$CI_COMMIT_REF_NAME" -w "$CI_COMMIT_REF_NAME" docs docs/_build/html
  artifacts:
    paths: [docs/_build]
    expire_in: 1 week
    when: always


deploy_staging:
  extends: .deploy_staging_v2

deploy_stable:
  extends: .deploy_stable_v2


deploy_docs:
  stage: deploy
  tags: [linux, docker]
  image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:3.6-18.04-1.1.0
  dependencies: []
  only: [master, tags]
  script:
    - apt-get update && apt-get install -y graphviz
    - python setup.py install
    - pip install -r docs/requirements.txt
    - ./ci/set_git_config.sh
    - sphinx-versioning push docs gh-pages .
