# -*- coding: utf-8 -*-
# (c) Copyright 2020 Sensirion AG, Switzerland

##############################################################################
##############################################################################
#                 _____         _    _ _______ _____ ____  _   _
#                / ____|   /\  | |  | |__   __|_   _/ __ \| \ | |
#               | |       /  \ | |  | |  | |    | || |  | |  \| |
#               | |      / /\ \| |  | |  | |    | || |  | | . ` |
#               | |____ / ____ \ |__| |  | |   _| || |__| | |\  |
#                \_____/_/    \_\____/   |_|  |_____\____/|_| \_|
#
#     THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED MANUALLY!
#
# Generator:    sensirion-shdlc-interface-generator 0.8.2
# Product:      SVM40
# Version:      0.3.0
#
##############################################################################
##############################################################################

# flake8: noqa

from __future__ import absolute_import, division, print_function
from sensirion_shdlc_driver.command import ShdlcCommand
from struct import pack, unpack

import logging
log = logging.getLogger(__name__)


class Svm40CmdDeviceResetBase(ShdlcCommand):
    """
    SHDLC command 0xD3: "Device Reset".
    """

    def __init__(self, *args, **kwargs):
        """
        Constructor.
        """
        super(Svm40CmdDeviceResetBase, self).__init__(
            0xD3, *args, **kwargs)


class Svm40CmdDeviceReset(Svm40CmdDeviceResetBase):
    """
    Device Reset Command

    Executs a reset on the device.

    .. note:: The device will reply before executing the reset. If the command
              is send with broadcast, the reset is done directly after the
              reception of the command.
    """

    def __init__(self):
        """
        Constructor.
        """
        super(Svm40CmdDeviceReset, self).__init__(
            data=[],
            max_response_time=0.05,
            post_processing_time=0.1,
            min_response_length=0,
            max_response_length=0
        )
